export const SKILLS = [
    {
        id: 1,
        key: "html",
        value: "HTML",
        skillLevel: 100,
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim debitis dicta. `,
        img: "image/skill/html.svg",
    },
    {
        id: 2,
        key: "css",
        value: "CSS",
        skillLevel: 100,
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim debitis dicta. `,
        img: "image/skill/css.svg",
    },
    {
        id: 3,
        key: "javasript",
        value: "JavaSript",
        skillLevel: 100,
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim debitis dicta. `,
        img: "image/skill/javascript.svg",
    },
    {
        id: 4,
        key: "react",
        value: "React",
        skillLevel: 78,
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim debitis dicta. `,
        img: "image/skill/react.svg",
    },
    {
        id: 5,
        key: "angular",
        value: "Angular",
        skillLevel: 20,
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim debitis dicta. `,
        img: "image/skill/angular.svg",
    },
    {
        id: 6,
        key: "vue",
        value: "Vue JS",
        skillLevel: 18.45,
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim debitis dicta. `,
        img: "image/skill/vue.svg",
    },
    {
        id: 7,
        key: "web-design",
        value: "Web Design",
        skillLevel: 70,
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim debitis dicta. `,
        img: "image/skill/graphic-design.svg",
    },
    {
        id: 8,
        key: "wordpress",
        value: "WordPress",
        skillLevel: 32,
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim debitis dicta. `,
        img: "image/skill/wordpress.svg",
    },
    {
        id: 9,
        key: "phyton",
        value: "Phyton",
        skillLevel: 80,
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim debitis dicta. `,
        img: "image/skill/python.svg",
    },
    {
        id: 10,
        key: "graphics",
        value: "Graphics",
        skillLevel: 75,
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim debitis dicta. `,
        img: "image/skill/graphic-design.svg",
    },
];

export const PROJECTS = [
    {
        id: 1,
        key: "sync-dash",
        dataType: "web development",
        title: "Sync Dashboard",
        description: `A web apllication with customizable user interfaces, subluquent eye catching designs, with nice User Experience`,
        previewImg: "image/small/0.png",
        webViewImg: [
            "image/large/a1.png",
            "image/large/a2.png",
            "image/large/a3.png",
            "image/large/a4.png",
            "image/large/a5.png",
            "image/large/a6.png",
        ],
        link: {
            git: "https://github/Invalid8/wave.io",
            host: "https://sync-dash.netlify.app",
        },
    },
    {
        id: 2,
        key: "eSmart",
        dataType: "web development",
        title: "Economy Smart",
        description: `A web apllication with customizable user interfaces, subluquent eye catching designs, with nice User Experience`,
        previewImg: "image/small/1.png",
        webViewImg: ["image/large/b1.png"],
        link: {
            git: "https://github/Invalid8/e-smart",
            host: "https://e-smart.netlify.app",
        },
    },
    {
        id: 3,
        key: "todo Python",
        dataType: "Programming",
        title: "Todo App - Phyton",
        description: `A phyton apllication with customizable user interfaces, subluquent eye catching designs, with nice User Experience`,
        previewImg: "image/small/null.png",
        webViewImg: ["image/small/null.png"],
        link: {
            git: "https://github/Invalid8/TODO-PYTHON-APP",
            host: "",
        },
    },
    {
        id: 4,
        key: "build",
        dataType: "web development",
        title: "Build",
        description: `A web apllication with customizable user interfaces, subluquent eye catching designs, with nice User Experience`,
        previewImg: "image/small/3.png",
        webViewImg: [
            "image/large/e1.png",
            "image/large/e2.png",
            "image/large/e3.png",
            "image/large/e4.png",
            "image/large/e5.png",
        ],
        link: {
            git: "https://github/Invalid8/build33",
            host: "https://build33.netlify.app",
        },
    },
    {
        id: 5,
        key: "fruity",
        dataType: "web development",
        title: "Fruit Tac Toe",
        description: `A web game with customizable user interfaces, subluquent eye catching designs, with nice User Experience`,
        previewImg: "image/small/4.png",
        webViewImg: [
            "image/large/f1.png",
            "image/large/f2.png",
            "image/large/f3.png",
            "image/large/f4.png",
        ],
        link: {
            git: "https://github/Invalid8/fruit-tac-toe",
            host: "https://fruit-tac-toe.netlify.app",
        },
    },
    {
        id: 6,
        key: "marvel",
        dataType: "web development",
        title: "Marvel Hero Board",
        description: `A web apllication with customizable user interfaces, subluquent eye catching designs, with nice User Experience`,
        previewImg: "image/small/5.png",
        webViewImg: [
            "image/large/g1.png",
            "image/large/g2.png",
            "image/large/g3.png",
            "image/large/g4.png",
            "image/large/g5.png",
        ],
        link: {
            git: "https://github/Invalid8/marvel-hero-board",
            host: "https://marvel-hero-board.netlify.app",
        },
    },
    {
        id: 7,
        key: "condra",
        dataType: "web development",
        title: "Condra Editor",
        description: `A web apllication with customizable user interfaces, subluquent eye catching designs, with nice User Experience`,
        previewImg: "image/small/0.png",
        webViewImg: ["image/large/g4.png"],
        link: {
            git: "https://github/Invalid8/condora",
            host: "https://condora.netlify.app",
        },
    },
];
